JNG-4250 Add PSM Archetype
BlackBeltTechnology/judo-psm-archetype pull request #1
Opened 2022-11-08 01:06 UTC by robertcsakany

<table>
<td>
  <a href="https://blackbelt.atlassian.net/browse/JNG-4250" title="JNG-4250" target="_blank"><img alt="Story" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />JNG-4250</a>  Add PSM generator archetype
  </td></table>
  <br />

2022-11-08 22:19 UTC, bencegelei approved these changes

2022-11-09 13:02 UTC, noherczeg requested changes

2022-11-09 13:02 UTC, noherczeg commented on judo-psm-archetype-generator/pom.xml
> +            <artifactId>org.eclipse.emf.ecore</artifactId>
Do we really need EMF stuff here?

2022-11-09 13:02 UTC, noherczeg commented on judo-psm-archetype-generator/src/main/java/hu/blackbelt/judo/psm/archetype/generator/GeneratorTemplate.java
> + *     <li>factoryExpression: A SpringEL Expression which can result a collection which will be used as list ofg generated output. The collection's elements is used
"ofg"?

2022-11-09 13:02 UTC, noherczeg commented on judo-psm-archetype-generator/src/test/java/hu/blackbelt/judo/psm/archetype/generator/Northwind2UiApplicationTest.java
> +public class Northwind2UiApplicationTest {
UI?

2022-11-09 13:02 UTC, noherczeg commented on judo-psm-archetype-generator/src/test/resources/override1/test1/actorname.hbs
> +Name: {{ actorType.name }}
How can this work if some actor helper thingy was commented out in one of the files above?

2022-11-09 13:02 UTC, noherczeg commented on judo-psm-archetype-maven-plugin/README.adoc
> +- Maven 3.6 and Java 11
3.6?

2022-11-09 13:02 UTC, noherczeg commented on judo-psm-archetype-maven-plugin/README.adoc
> +For code generation handlebars templates is used. The `<project type>-project.yaml` file
templates -> template.

2022-11-09 13:02 UTC, noherczeg commented on judo-psm-archetype-maven-plugin/README.adoc
> +To decorate `main.dart.hbs,` put `main.dart.override.hbs` file. The original content can be referenced:
Dart? :)

2022-11-09 13:02 UTC, noherczeg commented on judo-psm-archetype-maven-plugin/README.adoc
> +{{> flutter/lib/main.dart.hbs }}
Flutter? :D

2022-11-09 13:02 UTC, noherczeg commented on judo-psm-archetype-maven-plugin/pom.xml
> +			<artifactId>swagger-core</artifactId>
Swagger?

2022-11-09 13:46 UTC, gaborflorian approved these changes

2022-11-09 20:36 UTC, robertcsakany commented on judo-psm-archetype-generator/pom.xml
> +            <artifactId>org.eclipse.emf.ecore</artifactId>
Removed

2022-11-09 20:39 UTC, robertcsakany commented on judo-psm-archetype-generator/src/test/resources/override1/test1/actorname.hbs
> +Name: {{ actorType.name }}
For PSM model there is an implicit helper.

2022-11-23 07:58 UTC, merged